version: "3.5"

services:
  local-secret:
    image: ghcr.io/scrtlabs/localsecret:v1.3.1
    ports:
      - 9091:9091
      - 26657:26657
      - 1317:1317
      - 5000:5000
    healthcheck:
      test: ["CMD-SHELL", "secretcli status"]
      interval: 10s
      timeout: 5s
      retries: 8
